if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("ProfileCometActionFollowingStatusHandler_handler$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a={alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},b={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null};return{kind:"SplitOperation",metadata:{},name:"ProfileCometActionFollowingStatusHandler_handler$normalization",selections:[{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"profile_action",plural:!1,selections:[a,{alias:null,args:null,concreteType:"User",kind:"LinkedField",name:"profile_owner",plural:!1,selections:[b,{alias:null,args:null,kind:"ScalarField",name:"subscribe_status",storageKey:null}],storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"render_location",storageKey:null},b],storageKey:null},{alias:null,args:[{kind:"Literal",name:"supported",value:["XFBProfileSubscribedActionsRenderer","XFBProfilePlusSubscribedActionsRenderer"]}],concreteType:null,kind:"LinkedField",name:"subscibed_actions_renderer",plural:!1,selections:[a,{kind:"InlineFragment",selections:[{args:null,documentName:"ProfileCometActionFollowingStatusHandler_handler",fragmentName:"ProfileCometSubscribedActionsRenderer_renderer",fragmentPropName:"renderer",kind:"ModuleImport"}],type:"XFBProfileSubscribedActionsRenderer",abstractKey:null},{kind:"InlineFragment",selections:[{args:null,documentName:"ProfileCometActionFollowingStatusHandler_handler",fragmentName:"ProfilePlusSubscribedActionsRenderer_renderer",fragmentPropName:"renderer",kind:"ModuleImport"}],type:"XFBProfilePlusSubscribedActionsRenderer",abstractKey:null}],storageKey:'subscibed_actions_renderer(supported:["XFBProfileSubscribedActionsRenderer","XFBProfilePlusSubscribedActionsRenderer"])'}]}}();e.exports=a}),null);
__d("ProfileCometActionFollowingStatusHandler_handler.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"ProfileCometActionFollowingStatusHandler_handler",selections:[{kind:"RequiredField",field:{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"profile_action",plural:!1,selections:[{kind:"RequiredField",field:{alias:null,args:null,concreteType:"User",kind:"LinkedField",name:"profile_owner",plural:!1,selections:[{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},action:"THROW",path:"profile_action.profile_owner.id"},{alias:null,args:null,kind:"ScalarField",name:"subscribe_status",storageKey:null}],storageKey:null},action:"THROW",path:"profile_action.profile_owner"},{alias:null,args:null,kind:"ScalarField",name:"render_location",storageKey:null}],storageKey:null},action:"THROW",path:"profile_action"},{alias:null,args:[{kind:"Literal",name:"supported",value:["XFBProfileSubscribedActionsRenderer","XFBProfilePlusSubscribedActionsRenderer"]}],concreteType:null,kind:"LinkedField",name:"subscibed_actions_renderer",plural:!1,selections:[{kind:"InlineFragment",selections:[{args:null,documentName:"ProfileCometActionFollowingStatusHandler_handler",fragmentName:"ProfileCometSubscribedActionsRenderer_renderer",fragmentPropName:"renderer",kind:"ModuleImport"}],type:"XFBProfileSubscribedActionsRenderer",abstractKey:null},{kind:"InlineFragment",selections:[{args:null,documentName:"ProfileCometActionFollowingStatusHandler_handler",fragmentName:"ProfilePlusSubscribedActionsRenderer_renderer",fragmentPropName:"renderer",kind:"ModuleImport"}],type:"XFBProfilePlusSubscribedActionsRenderer",abstractKey:null}],storageKey:'subscibed_actions_renderer(supported:["XFBProfileSubscribedActionsRenderer","XFBProfilePlusSubscribedActionsRenderer"])'}],type:"ProfileActionFollowingStatusHandler",abstractKey:null};e.exports=a}),null);
__d("ProfileCometActionFollowingMenuQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7889005517792068"}),null);
__d("ProfileCometActionFollowingMenuQuery$Parameters",["ProfileCometActionFollowingMenuQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometActionFollowingMenuQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometActionFollowingMenuQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometSubscribedActionsRenderer_renderer$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"ProfileCometSubscribedActionsRenderer_renderer$normalization",selections:[{alias:null,args:null,concreteType:"User",kind:"LinkedField",name:"profile_owner",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null}]};e.exports=a}),null);
__d("ProfileCometSubscribedActionsRenderer_renderer.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"ProfileCometSubscribedActionsRenderer_renderer",selections:[{kind:"RequiredField",field:{alias:null,args:null,concreteType:"User",kind:"LinkedField",name:"profile_owner",plural:!1,selections:[{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},action:"THROW",path:"profile_owner.id"}],storageKey:null},action:"THROW",path:"profile_owner"}],type:"XFBProfileSubscribedActionsRenderer",abstractKey:null};e.exports=a}),null);
__d("ProfileCometActionFollowingStatusHandler.react",["CometRelay","ProfileCometActionFollowingStatusHandler_handler.graphql","ProfilePlusFollowChainingContext.react","react","recoverableViolation","requireDeferred","useMinifiedProductAttribution"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react");e=d("react");var j=e.useCallback,k=e.useContext,l=e.useState,m=c("requireDeferred")("CometUserFollowMutation").__setRef("ProfileCometActionFollowingStatusHandler.react");function a(a){var e=a.children,f=a.handler;a=a.popoverPosition;var g=l(!1),n=g[0],o=g[1],p=d("CometRelay").useRelayEnvironment();g=d("CometRelay").useFragment(h!==void 0?h:h=b("ProfileCometActionFollowingStatusHandler_handler.graphql"),f);var q=g.profile_action.profile_owner.id,r=(f=g.profile_action)==null?void 0:(f=f.profile_owner)==null?void 0:f.subscribe_status,s=((f=g.profile_action)==null?void 0:f.render_location)||"WWW_COMET_FOLLOWING_MENU";f=k(d("ProfilePlusFollowChainingContext.react").ProfilePlusFollowChainingContext);var t=f.setShouldShowFollowChaining,u="PROFILE",v=c("useMinifiedProductAttribution")();f=j(function(){if(r==="CAN_SUBSCRIBE"){o(!0);var a={actionRenderLocation:s,navigationChain:v,onError:function(){o(!1)},onSuccess:function(){o(!1)},subscribeLocation:u,userID:q};m.onReady(function(b){b=b.enqueue;return b(p,a)});t(!0)}},[p,q,v,s,t,r]);if(r==="IS_SUBSCRIBED")return i.jsx(d("CometRelay").MatchContainer,{match:g.subscibed_actions_renderer,props:{actionRenderLocation:s,children:e,popoverPosition:a,shouldIncludeTrackingData:!1,subscribeLocation:u}});if(r==="CANNOT_SUBSCRIBE"){c("recoverableViolation")("Rendering following status action for user that cannot be followed","profile_comet");return e({disabled:!0})}return e({disabled:n,onPress:f})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("ProfileCometActionFollowingMenu.entrypoint",["JSResourceForInteraction","ProfileCometActionFollowingMenuQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.profileID;return{queries:{queryReference:{parameters:c("ProfileCometActionFollowingMenuQuery$Parameters"),variables:{profileID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("ProfileCometActionFollowingMenu.react").__setRef("ProfileCometActionFollowingMenu.entrypoint")};g["default"]=a}),98);
__d("ProfileCometSubscribedActionsRenderer.react",["CometEntryPointPopoverTrigger.react","CometRelay","ProfileCometActionFollowingMenu.entrypoint","ProfileCometSubscribedActionsRenderer_renderer.graphql","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react");function a(a){var e=a.children,f=a.popoverPosition;a=a.renderer;a=d("CometRelay").useFragment(h!==void 0?h:h=b("ProfileCometSubscribedActionsRenderer_renderer.graphql"),a);return i.jsx(c("CometEntryPointPopoverTrigger.react"),{entryPointParams:{profileID:a.profile_owner.id},otherProps:{},popoverEntryPoint:c("ProfileCometActionFollowingMenu.entrypoint"),position:f,preloadTrigger:"button",children:function(a,b,c,d,f,g){return e({onHoverIn:d,onHoverOut:f,onPress:b,onPressIn:g,ref:a})}})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("FollowerInviteFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1827823");c=b("FalcoLoggerInternal").create("follower_invite",a);e.exports=c}),null);
__d("PagesFollowerInviteImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1845728");c=b("FalcoLoggerInternal").create("pages_follower_invite_impression",a);e.exports=c}),null);
__d("CometSinglePageMenuRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4778347472252395"}),null);
__d("PagesCometEventsAdminWithTabsLayoutRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4867023886680433"}),null);
__d("ProfilePlusCometActionFollowingDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="3809772372481214"}),null);/*FB_PKG_DELIM*/
__d("GroupsCometGrowthPreferencesFilterInvitesContext",["react"],(function(a,b,c,d,e,f,g){"use strict";d("react");a=d("react").createContext;b={currentCategorizedFilter:null,setCurrentCategorizedFilter:function(){}};c=a(b);g["default"]=c}),98);
__d("GroupsCometGrowthPreferencesMemberOfOtherGroupsContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react").createContext;b={selectedGrowthGroups:[],setSelectedGrowthGroups:function(){}};c=a(b);g["default"]=c}),98);
__d("GroupsCometInviteFriendsDialogDispatchContextDispatcher",["emptyFunction","react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(c("emptyFunction"));g["default"]=b}),98);
__d("PagesCometInviteFriendsListPlaceholder.react",["CometProfileListRowLoadingState.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){a=a.count;return h.jsx("div",{children:Array.apply(null,Array(a)).map(function(a,b){return h.jsx(c("CometProfileListRowLoadingState.react"),{},b)})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("XCometPageGroupsTabControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/{vanity}/groups/",Object.freeze({ref:""}),void 0);b=a;g["default"]=b}),98);
__d("PagesCometInviteFriendsGroupSelectorMenuQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4325460217506838"}),null);