if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("LSVerifyContactRowExists",["LSIssueNewTask"],(function(a,b,c,d,e,f){function a(){var a=arguments,c=a[a.length-1];c.n;var d=[],e=[],f;return c.seq([function(e){return c.ftr(c.db.table(7).fetch([[[a[0]]]]),function(b){return c.i64.eq(b.id,a[0])&&c.i64.eq([0,1],[0,1])}).next().then(function(e){var g=e.done;e.value;return g?c.seq([function(b){return d[0]=a[3]==null?"":a[3],c.fe(c.ftr(c.db.table(7).fetch([[[a[0]]]]),function(b){return c.i64.eq(b.id,a[0])&&c.i64.eq([0,1],[0,1])&&c.i64.lt(b.authorityLevel,a[14])}),function(a){return a["delete"]()})},function(b){return c.db.table(7).add({id:a[0],profilePictureUrl:a[2]==null?"":a[2],profilePictureFallbackUrl:a[5],name:d[0],secondaryName:a[20],normalizedNameForSearch:d[0],isMemorialized:a[9],blockedByViewerStatus:a[11],canViewerMessage:a[12],profilePictureLargeUrl:"",isMessengerUser:!0,rank:0,contactType:a[4],contactTypeExact:[0,0],requiresMultiway:!1,authorityLevel:a[14],workForeignEntityType:[0,0],capabilities:a[15],capabilities2:a[16],contactViewerRelationship:a[19],gender:a[18]})},function(e){return d[1]=new c.Map(),d[1].set("contact_id",a[0]),d[2]=c.toJSON(d[1]),c.sp(b("LSIssueNewTask"),"cpq_v2",[0,207],d[2],f,f,[0,0],f)}]):0})},function(a){return c.resolve(e)}])}e.exports=a}),null);
__d("LSUpsertReaction",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1];b.n;var c=[];return b.seq([function(c){return b.db.table(8).put({threadKey:a[0],messageId:a[2],actorId:a[3],timestampMs:a[1],reaction:a[4],authorityLevel:a[5]})},function(a){return b.resolve(c)}])}e.exports=a}),null);
__d("CometImageCover.react",["BaseImage_DEPRECATED.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");e=d("react");var i=e.useCallback,j=e.useRef,k=e.useState;d=function(){var a=document.documentElement;return a==null?!0:Boolean("objectFit"in a.style)}();function a(a){a.alt;var b=a.loading,d=a.onError,e=a.onLoad,f=a.src,g=a.style;a=babelHelpers.objectWithoutPropertiesLoose(a,["alt","loading","onError","onLoad","src","style"]);var l=k(null),m=l[0],n=l[1],o=j();l=i(function(){var a=o.current;if(a==null||!(a instanceof HTMLImageElement)||typeof a.src!=="string")return;n(a.src);e!=null&&e()},[e]);return m!=null?h.jsx("div",{className:"k4urcfbm bixrwtb6 datstx6m q9uorilb",style:babelHelpers["extends"]({backgroundImage:"url("+m+")",backgroundPosition:"center center",backgroundSize:"cover"},g)}):h.jsx(c("BaseImage_DEPRECATED.react"),babelHelpers["extends"]({},a,{className:"ttbfdpzt do00u71z",loading:b||void 0,onError:d,onLoad:l,ref:o,src:f,style:g}))}a.displayName=a.name+" [from "+f.id+"]";function b(a){return h.jsx(c("BaseImage_DEPRECATED.react"),babelHelpers["extends"]({className:"k4urcfbm bixrwtb6 datstx6m q9uorilb"},a))}b.displayName=b.name+" [from "+f.id+"]";e=d?b:a;g["default"]=e}),98);
__d("LSContactGenderToGenderConst.bs",["GenderConst","LSContactGender.bs","bs_caml"],(function(a,b,c,d,e,f){"use strict";function a(a){if(b("bs_caml").i64_eq(a,b("LSContactGender.bs").female))return b("GenderConst").FEMALE_SINGULAR;else if(b("bs_caml").i64_eq(a,b("LSContactGender.bs").male))return b("GenderConst").MALE_SINGULAR;else if(b("bs_caml").i64_eq(a,b("LSContactGender.bs").neuter))return b("GenderConst").NEUTER_SINGULAR;else return b("GenderConst").NOT_A_PERSON}f.make=a}),null);
__d("MWCMInboxHeaderCommunityGroupName.bs",["ReQL.bs","ReQLSuspense","bs_curry","react","useReStore"],(function(a,b,c,d,e,f){"use strict";var g,h=g||b("react");function i(a){return a}function a(a){var c=a.thread;a=a.renderWrapper;a=a!==void 0?a:i;var d=b("useReStore")(),e=b("ReQLSuspense").useFirst(h.useMemo(function(){return b("ReQL.bs").getKeyRange(b("ReQL.bs").fromTableAscending(d.table("community_folders")),{hd:c.parentThreadKey,tl:0})},[d,JSON.stringify(c.parentThreadKey)]));if(e!==void 0)return h.jsx(h.Fragment,{children:b("bs_curry")._1(a,e.name)});else return null}c=a;f.defaultRenderWrapper=i;f.make=c}),null);
__d("MWChatTypingIndicator.bs",["react","stylex"],(function(a,b,c,d,e,f){"use strict";var g,h,i=g||b("react");c="rqt66bd7-B";var j={root:{alignItems:"bp9cbjyn",display:"j83agx80",height:"kmzbrmfl"},dot:{animationName:"d75kxgp9",animationDuration:"kv069q7b",animationIterationCount:"ee40wjg4",animationTimingFunction:"rr7aif1o",borderTopStartRadius:"s8bnoagg",borderTopEndRadius:"bn9qtmzc",borderBottomEndRadius:"hp05c5td",borderBottomStartRadius:"b6jg2yqc",display:"q9uorilb",height:"mw227v9j",marginEnd:"ditlmg2l",marginStart:"nvdbi5me",width:"loos5mxf",backgroundColor:"aph9nnby"},dot1:{animationDelay:"tv4077gy"},dot2:{animationDelay:"oeefd0zo"},dot3:{animationDelay:"dg03pwpq"}};function a(a){return i.jsxs("div",{className:(h||(h=b("stylex")))(j.root),children:[i.jsx("div",{className:h(j.dot,j.dot1)}),i.jsx("div",{className:h(j.dot,j.dot2)}),i.jsx("div",{className:h(j.dot,j.dot3)})]})}d=a;f.dotAnimation=c;f.styles=j;f.make=d}),null);
__d("LSContactIdType.bs",["bs_caml_int64"],(function(a,b,c,d,e,f){"use strict";a=b("bs_caml_int64").zero;c=b("bs_caml_int64").one;d=[0,2];f.unknown=a;f.fbid=c;f.smsLocalId=d}),null);
__d("MWV2EnsureThatChatTabExists.bs",["LS.bs","LSAuthorityLevel.bs","LSContactBlockedByViewerStatus.bs","LSContactGender.bs","LSContactIdType.bs","LSContactType.bs","LSContactViewerRelationship.bs","LSContactWorkForeignEntityType.bs","LSDatabaseType.bs","LSMessagingThreadTypeUtil.bs","LSTransaction.bs","LSVerifyContactRowExists","LSVerifyThreadRowExists","Promise","bs_curry","cr:1127","promiseDone","react","useReStore"],(function(a,b,c,d,e,f){"use strict";var g,h=g||b("react");function a(a,c){var d=b("useReStore")();h.useEffect(function(){var e=function(e){if(b("LSMessagingThreadTypeUtil.bs").isOneToOne(c))return b("LSTransaction.bs").run(d,function(c){return b("LSVerifyContactRowExists")(a,b("LSContactIdType.bs").fbid,void 0,void 0,b("LSContactType.bs").user,void 0,void 0,void 0,void 0,!1,!1,b("LSContactBlockedByViewerStatus.bs").unblocked,void 0,!1,b("LSAuthorityLevel.bs").clientPartial,void 0,void 0,b("LSContactWorkForeignEntityType.bs").unknown,b("LSContactGender.bs").unknown,b("LSContactViewerRelationship.bs").unknown,void 0,b("LS.bs").make(c))},"readWrite");else return b("Promise").resolve(void 0)};b("promiseDone")(e(void 0).then(function(e){return!(b("cr:1127")==null)&&b("LSMessagingThreadTypeUtil.bs").isSecure(c)?b("bs_curry")._2(b("cr:1127").call,d,a):b("LSTransaction.bs").run(d,function(d){return b("LSVerifyThreadRowExists")(a,c,b("LSDatabaseType.bs").mailbox,b("LS.bs").make(d))},"readWrite")}),void 0,void 0)},[d,JSON.stringify(a),JSON.stringify(c)])}c=b("cr:1127");f.$MAWVerifyExistingThreadExists$requireCondXplat=b("cr:1127");f.mawVerifyExistingThreadExists=c;f.useHook=a}),null);
__d("CometEmoji.bs",["CometEmoji.react"],(function(a,b,c,d,e,f){"use strict";a=b("CometEmoji.react");f.make=a}),null);
__d("EmojiFormat.bs",[],(function(a,b,c,d,e,f){"use strict";function g(a){return a.split("_").map(function(a){return parseInt(a,16)})}function a(a){return a.map(function(a){return a.toString(16)}).join("_")}function h(a){return a.map(function(a){return String.fromCodePoint(a)}).join("")}function b(a){return h(g(a))}f.codeStringToCodeArray=g;f.codeArrayToCodeString=a;f.codeArrayToUnicode=h;f.codeStringToUnicode=b}),null);
__d("EmojiLikeConstants",["EmojiStaticConfig"],(function(a,b,c,d,e,f,g){"use strict";a=Object.freeze({XSMALL:"xsmall",SMALL:"small",MEDIUM:"medium",LARGE:"large"});b={dp16:"xsmall",dp32:"small",dp64:"medium",db64:"medium",dp128:"large"};d=Object.freeze({PICKER:"picker",HOT_LIKE:"hot_like"});e=[983040];f="hot_emoji_source";var h="hot_emoji_size",i="emoji_like",j="\ud83d\udc4d",k=[128077];g.sizeMap=c("EmojiStaticConfig").sizeMap;g.size=a;g.sizeMapTransfer=b;g.source=d;g.FB_THUMBS_UP_EMOJI=e;g.SOURCE_TAG_PREFIX=f;g.TAG_PREFIX_NEW=h;g.TAG_PREFIX_OLD=i;g.THUMBS_UP_EMOJI=j;g.THUMBS_UP_EMOJI_CODES=k}),98);
__d("useLexicalIsTextContentEmpty",["cr:1022"],(function(a,b,c,d,e,f){e.exports=b("cr:1022")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @noflow
* @nolint
* @preventMunge
* @preserve-invariant-messages
* @generated
* @preserve-whitespace
* @fullSyntaxTransform
 */__d("useLexicalIsTextContentEmpty.prod",["LexicalText","react"],(function $module_useLexicalIsTextContentEmpty_prod(global,require,requireDynamic,requireLazy,module,exports){var c_react;
var e=c_react||(c_react=require("react")),f="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement?e.useLayoutEffect:e.useEffect;module.exports=function(a,c){var _e$useState=e.useState(a.getEditorState().read(require("LexicalText").$isRootTextContentEmptyCurry(a.isComposing(),c))),g=_e$useState[0],h=_e$useState[1];f(function(){return a.addListener("update",function(_ref){var d=_ref.editorState;var k=a.isComposing();d=d.read(require("LexicalText").$isRootTextContentEmptyCurry(k,c));h(d);});},[a,c]);return g;};}),null);